### ISSUE TITLE
Prof. Lockhart card name entered wrong

### ISSUE THREAD

**Issue by StefanGiovanni** [Tressley/hpjson#19] opened 2020-08-02 13:23 UTC
He's entered as "Lockheart".

Might need to tell Johann and Ernest to update after you push the update. :)

**Comment by perezdev** [comment] 2020-08-02 15:18
Duplicate of #17

**Comment by Tressley** [comment] 2020-08-06 11:32
This was fixed in 2faf147.

**Closed by Tressley** 2020-08-06 11:32 UTC
